## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
    #  - STATEFUL-APP-DEPLOY
    #  - APP-FUNC-TEST
    #  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/openebs/e2e-eks/script/utils"

## Setup the kubernetes cluster

eks-cluster:
  image: atulabhi/kops:v10
  stage: CLUSTER-SETUP 
  script:
    - chmod 775 ./script/eks 
    - ./script/eks
  artifacts:
    paths:
      - .kube/

## Setup OpenEBS control plane

openebs-eks-deploy:
  image: atulabhi/kops:v10
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - eks-cluster
  script: 
   - chmod 775 ./script/provider/infra-setup
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

## Define a job template for app deployers
cleanup-eks:
  when: always
  image: atulabhi/kops:v10
  dependencies:
    - eks-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/eks-cleanup
    - ./script/eks-cleanup
